### ISSUE TITLE
growl error

### ISSUE THREAD

**Issue by vredeling** [paiq/notifier#1]
After installing growl 1.3 (on mac osx lion 10.7) I get an error from the notifier at startup saying that growl is not installed. I believe this is erroneous.

**Comment by vredeling** [comment]
This method http://growl.info/documentation/appconfigs/skype.php also works for the notifier. (replacing the built-in framework with growl version detective)

**Comment by EmielM** [comment]
Thanks for the feedback. Just for the record, I think the development branch should not exhibit this behavior (unsure what version is currently deployed on paiq.nl). If it does, the error is probably upstream at https://github.com/EmielM/tinygrowl.
